widget
~~~~~~

**typ**: ``string`` **domyślnie**: ``choice``

Podstawowym sposobem, w jakim pole powinno być renderowane może być jedną z następujących czynności:

* ``choice``: renderuje trzy pola wyboru. Kolejność wybierania definiuje się na podstawie
  opcji `pattern`_.

* ``text``: renderuje trzy pola tekstowe (miesiąc, dzień, rok).

* ``single_text``: renderuje pojedyncze pole tekstowe. Tekst wpisany przez użytkownika jest
  sprawdzany na podstawie opcji `format`_.
