* **Opcje konfiguracyjne**:
  
  Czy kiedykolwiek zastanawiałeś się, jakie opcje konfiguracji masz dostępne w postaci plików
  takich jak ``app/config/config.yml``? W tej części dostępne są wszystkie konfiguracje
  podzielone na klucze (np. ``framework``), które definiują wszystkie możliwe konfiguracje
  sekcji z Symfony2.

  * :doc:`framework </reference/configuration/framework>`
  * :doc:`doctrine </reference/configuration/doctrine>`
  * :doc:`security </reference/configuration/security>`
  * :doc:`assetic </reference/configuration/assetic>`
  * :doc:`swiftmailer </reference/configuration/swiftmailer>`
  * :doc:`twig </reference/configuration/twig>`
  * :doc:`monolog </reference/configuration/monolog>`
  * :doc:`web_profiler </reference/configuration/web_profiler>`

* **Formularze i walidatory**

  * :doc:`Typy formularza </reference/forms/types>`
  * :doc:`Walidacja poprzez ograniczenia </reference/constraints>`
  * :doc:`Funkcje formularza w Twig </reference/forms/twig_reference>`

* **Pozostałe**

  * :doc:`/reference/dic_tags`
  * :doc:`/reference/YAML`
  * :doc:`/reference/requirements`
