* **Opcje konfiguracyjne**

  Czy kiedykolwiek zastanawiałeś się, jakie opcje konfiguracji masz dostępne w postaci plików
  takich jak ``app/config/config.yml``? W tej części dostępne są wszystkie konfiguracje
  podzielone na klucze (np. ``framework``), które definiują wszystkie możliwe
  sekcje konfiguracji z Symfony2.

  * :doc:`framework </reference/configuration/framework>`
  * :doc:`doctrine </reference/configuration/doctrine>`
  * :doc:`security </reference/configuration/security>`
  * :doc:`assetic </reference/configuration/assetic>`
  * :doc:`swiftmailer </reference/configuration/swiftmailer>`
  * :doc:`twig </reference/configuration/twig>`
  * :doc:`monolog </reference/configuration/monolog>`
  * :doc:`web_profiler </reference/configuration/web_profiler>`

* :doc:`Konfiguracja Kernela (np. AppKernel) </reference/configuration/kernel>`

* **Formularze i walidacja**

  * :doc:`/reference/forms/types`
  * :doc:`/reference/constraints`
  * :doc:`/reference/forms/twig_reference`

* :doc:`/reference/twig_reference`

* **Pozostałe**

  * :doc:`/reference/dic_tags`
  * :doc:`/reference/requirements`
