Opcje konfiguracyjne
--------------------
  
  Czy kiedykolwiek zastanawiałeś się, jakie opcje konfiguracji masz dostępne w postaci plików
  takich jak ``app/config/config.yml``? W tej części dostępne są wszystkie konfiguracje
  podzielone na klucze (np. ``framework``), które definiują wszystkie możliwe
  sekcje konfiguracji z Symfony2.

  * :doc:`/reference/configuration/framework`
  * :doc:`/reference/configuration/doctrine`
  * :doc:`/reference/configuration/security`
  * :doc:`/reference/configuration/assetic`
  * :doc:`/reference/configuration/swiftmailer`
  * :doc:`/reference/configuration/twig`
  * :doc:`/reference/configuration/monolog`
  * :doc:`/reference/configuration/web_profiler`
  * :doc:`/reference/configuration/kernel`  

  
Formularze i walidacja
----------------------

  * :doc:`/reference/forms/types`
  * :doc:`/reference/constraints`
  * :doc:`/reference/forms/twig_reference`
  
  
Pozostałe
---------

  * :doc:`/reference/dic_tags`
  * :doc:`/reference/requirements`
  * :doc:`/reference/twig_reference`	