* **Kod**:

  * :doc:`Błędy </contributing/code/bugs>`
  * :doc:`Poprawki </contributing/code/patches>`
  * :doc:`Bezpieczeństwo </contributing/code/security>`
  * :doc:`Testy </contributing/code/tests>`
  * :doc:`Standardy kodowania</contributing/code/standards>`
  * :doc:`Konwencja</contributing/code/conventions>`
  * :doc:`Git</contributing/code/git>`
  * :doc:`Licencja </contributing/code/license>`

* **Dokumentacja**:

  * :doc:`Przegląd </contributing/documentation/overview>`
  * :doc:`Format </contributing/documentation/format>`
  * :doc:`Standardy dokumentacji </contributing/documentation/standards>`
  * :doc:`Tłumaczenia </contributing/documentation/translations>`
  * :doc:`Licencja </contributing/documentation/license>`

* **Społeczność**:

  * :doc:`Proces wydawania </contributing/community/releases>`
  * :doc:`Spotkania IRC </contributing/community/irc>`
  * :doc:`Inne zasoby </contributing/community/other>`
